-- Seed lab_orders for the last 7 days so Predictive Analytics dashboard shows real data.
-- Run: php admin/modules/lis/run_seed_lab_orders_predictive.php
-- Uses patient_id P001-P030 and test names from LIS; order_time spread across last 7 days.

INSERT INTO lab_orders (patient_id, test_name, order_time, priority, status) VALUES
('P001', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 6 DAY, ' 08:15:00'), 'medium', 'completed'),
('P002', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 6 DAY, ' 08:30:00'), 'high', 'completed'),
('P003', 'Creatinine', CONCAT(CURDATE() - INTERVAL 6 DAY, ' 09:00:00'), 'medium', 'completed'),
('P004', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 6 DAY, ' 09:20:00'), 'low', 'completed'),
('P005', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 6 DAY, ' 10:00:00'), 'medium', 'completed'),
('P006', 'ALT (SGPT)', CONCAT(CURDATE() - INTERVAL 6 DAY, ' 10:30:00'), 'high', 'completed'),
('P007', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 6 DAY, ' 11:00:00'), 'medium', 'completed'),
('P001', 'Creatinine', CONCAT(CURDATE() - INTERVAL 6 DAY, ' 11:30:00'), 'medium', 'completed'),
('P008', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 6 DAY, ' 14:00:00'), 'low', 'completed'),
('P009', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 6 DAY, ' 14:30:00'), 'medium', 'completed'),

('P002', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 07:45:00'), 'high', 'completed'),
('P010', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 08:00:00'), 'medium', 'completed'),
('P011', 'Creatinine', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 08:30:00'), 'medium', 'completed'),
('P012', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 09:00:00'), 'low', 'completed'),
('P003', 'ALT (SGPT)', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 09:30:00'), 'high', 'completed'),
('P013', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 10:00:00'), 'medium', 'completed'),
('P014', 'Blood Culture', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 10:45:00'), 'high', 'completed'),
('P004', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 11:15:00'), 'medium', 'completed'),
('P015', 'Creatinine', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 13:00:00'), 'medium', 'completed'),
('P016', 'Urine Culture', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 13:30:00'), 'low', 'completed'),
('P005', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 14:00:00'), 'medium', 'completed'),
('P017', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 5 DAY, ' 15:00:00'), 'medium', 'completed'),

('P006', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 08:00:00'), 'medium', 'completed'),
('P018', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 08:20:00'), 'high', 'completed'),
('P019', 'Creatinine', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 08:50:00'), 'medium', 'completed'),
('P007', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 09:15:00'), 'low', 'completed'),
('P020', 'ALT (SGPT)', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 09:45:00'), 'medium', 'completed'),
('P008', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 10:30:00'), 'medium', 'completed'),
('P021', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 11:00:00'), 'medium', 'completed'),
('P009', 'Creatinine', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 11:30:00'), 'low', 'completed'),
('P022', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 12:00:00'), 'medium', 'completed'),
('P010', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 14:00:00'), 'medium', 'completed'),
('P023', 'Blood Culture', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 14:30:00'), 'high', 'completed'),
('P011', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 4 DAY, ' 15:00:00'), 'medium', 'completed'),

('P012', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 07:30:00'), 'high', 'completed'),
('P024', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 08:00:00'), 'medium', 'completed'),
('P013', 'Creatinine', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 08:30:00'), 'medium', 'completed'),
('P025', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 09:00:00'), 'low', 'completed'),
('P014', 'ALT (SGPT)', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 09:30:00'), 'medium', 'completed'),
('P026', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 10:00:00'), 'medium', 'completed'),
('P015', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 10:30:00'), 'medium', 'completed'),
('P027', 'Urine Culture', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 11:00:00'), 'low', 'completed'),
('P016', 'Creatinine', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 11:45:00'), 'medium', 'completed'),
('P028', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 13:00:00'), 'medium', 'completed'),
('P017', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 13:30:00'), 'medium', 'completed'),
('P018', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 14:00:00'), 'high', 'completed'),
('P029', 'Creatinine', CONCAT(CURDATE() - INTERVAL 3 DAY, ' 15:00:00'), 'medium', 'completed'),

('P019', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 08:00:00'), 'medium', 'completed'),
('P030', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 08:25:00'), 'high', 'completed'),
('P020', 'Creatinine', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 08:50:00'), 'medium', 'completed'),
('P001', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 09:15:00'), 'low', 'completed'),
('P021', 'ALT (SGPT)', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 09:45:00'), 'medium', 'completed'),
('P002', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 10:15:00'), 'medium', 'completed'),
('P022', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 10:45:00'), 'medium', 'completed'),
('P023', 'Creatinine', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 11:15:00'), 'medium', 'completed'),
('P003', 'Blood Culture', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 11:45:00'), 'high', 'completed'),
('P024', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 13:00:00'), 'medium', 'completed'),
('P025', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 13:30:00'), 'medium', 'completed'),
('P004', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 14:00:00'), 'medium', 'completed'),
('P026', 'Creatinine', CONCAT(CURDATE() - INTERVAL 2 DAY, ' 14:30:00'), 'low', 'completed'),

('P005', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 07:45:00'), 'medium', 'completed'),
('P027', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 08:10:00'), 'high', 'completed'),
('P006', 'Creatinine', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 08:40:00'), 'medium', 'completed'),
('P028', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 09:00:00'), 'low', 'completed'),
('P007', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 09:30:00'), 'medium', 'completed'),
('P029', 'ALT (SGPT)', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 10:00:00'), 'medium', 'completed'),
('P008', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 10:30:00'), 'medium', 'completed'),
('P030', 'Creatinine', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 11:00:00'), 'medium', 'completed'),
('P009', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 11:30:00'), 'medium', 'completed'),
('P010', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 12:00:00'), 'low', 'completed'),
('P011', 'Blood Glucose (Fasting)', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 13:00:00'), 'high', 'completed'),
('P012', 'Urine Culture', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 13:30:00'), 'medium', 'completed'),
('P013', 'Complete Blood Count (CBC)', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 14:00:00'), 'medium', 'completed'),
('P014', 'Creatinine', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 14:30:00'), 'medium', 'completed'),
('P015', 'Hemoglobin', CONCAT(CURDATE() - INTERVAL 1 DAY, ' 15:00:00'), 'medium', 'completed'),

('P016', 'Complete Blood Count (CBC)', CONCAT(CURDATE(), ' 07:30:00'), 'medium', 'received'),
('P017', 'Blood Glucose (Fasting)', CONCAT(CURDATE(), ' 08:00:00'), 'high', 'processing'),
('P018', 'Creatinine', CONCAT(CURDATE(), ' 08:25:00'), 'medium', 'received'),
('P019', 'Hemoglobin', CONCAT(CURDATE(), ' 08:50:00'), 'low', 'completed'),
('P020', 'Complete Blood Count (CBC)', CONCAT(CURDATE(), ' 09:15:00'), 'medium', 'received'),
('P021', 'Blood Glucose (Fasting)', CONCAT(CURDATE(), ' 09:45:00'), 'medium', 'verification'),
('P022', 'ALT (SGPT)', CONCAT(CURDATE(), ' 10:00:00'), 'high', 'received'),
('P023', 'Complete Blood Count (CBC)', CONCAT(CURDATE(), ' 10:30:00'), 'medium', 'processing'),
('P024', 'Creatinine', CONCAT(CURDATE(), ' 11:00:00'), 'medium', 'received'),
('P025', 'Hemoglobin', CONCAT(CURDATE(), ' 11:30:00'), 'medium', 'completed'),
('P026', 'Blood Culture', CONCAT(CURDATE(), ' 12:00:00'), 'high', 'received'),
('P027', 'Complete Blood Count (CBC)', CONCAT(CURDATE(), ' 13:00:00'), 'medium', 'received'),
('P028', 'Blood Glucose (Fasting)', CONCAT(CURDATE(), ' 13:30:00'), 'medium', 'received'),
('P029', 'Creatinine', CONCAT(CURDATE(), ' 14:00:00'), 'low', 'received'),
('P030', 'Complete Blood Count (CBC)', CONCAT(CURDATE(), ' 14:30:00'), 'medium', 'received');
